

ALTER SESSION SET NLS_LANGUAGE = 'GERMAN';

ALTER SESSION SET NLS_DATE_FORMAT = 'DD.MM.YYYY';

ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'DD.MM.YYYY HH24:MI:SS';

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';

ALTER SESSION SET NLS_SORT = 'GERMAN';

ALTER SESSION SET NLS_COMP = 'LINGUISTIC';

ALTER SESSION SET NLS_TERRITORY = 'GERMANY';

ALTER SESSION SET TIME_ZONE = 'Europe/Berlin';


COMMIT;


SELECT   PARAMETER ,VALUE
    FROM nls_session_parameters 
ORDER BY 1;
/


