ALTER SESSION SET NLS_DATE_FORMAT = 'DD.MM.YYYY';

ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'DD.MM.YYYY HH24:MI:SS';

ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';

ALTER SESSION SET NLS_SORT = 'GERMAN';

ALTER SESSION SET NLS_COMP = 'LINGUISTIC';

COMMIT;